/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SellerIndexRouteImport } from './routes/seller/index'
import { Route as TIdRouteImport } from './routes/t.$id'
import { Route as SellerCreateRouteImport } from './routes/seller/create'
import { Route as TIdIndexRouteImport } from './routes/t.$id.index'
import { Route as TIdReceiptRouteImport } from './routes/t.$id.receipt'
import { Route as TIdProtectedRouteImport } from './routes/t.$id.protected'
import { Route as TIdPayRouteImport } from './routes/t.$id.pay'
import { Route as TIdIssueRouteImport } from './routes/t.$id.issue'
import { Route as TIdConfirmRouteImport } from './routes/t.$id.confirm'
import { Route as SellerTxnIdRouteImport } from './routes/seller/txn.$id'
import { Route as SellerShareIdRouteImport } from './routes/seller/share.$id'
import { Route as SellerTxnIdIndexRouteImport } from './routes/seller/txn.$id.index'
import { Route as SellerTxnIdRespondRouteImport } from './routes/seller/txn.$id.respond'
import { Route as SellerTxnIdDispatchRouteImport } from './routes/seller/txn.$id.dispatch'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerIndexRoute = SellerIndexRouteImport.update({
  id: '/seller/',
  path: '/seller/',
  getParentRoute: () => rootRouteImport,
} as any)
const TIdRoute = TIdRouteImport.update({
  id: '/t/$id',
  path: '/t/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerCreateRoute = SellerCreateRouteImport.update({
  id: '/seller/create',
  path: '/seller/create',
  getParentRoute: () => rootRouteImport,
} as any)
const TIdIndexRoute = TIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TIdRoute,
} as any)
const TIdReceiptRoute = TIdReceiptRouteImport.update({
  id: '/receipt',
  path: '/receipt',
  getParentRoute: () => TIdRoute,
} as any)
const TIdProtectedRoute = TIdProtectedRouteImport.update({
  id: '/protected',
  path: '/protected',
  getParentRoute: () => TIdRoute,
} as any)
const TIdPayRoute = TIdPayRouteImport.update({
  id: '/pay',
  path: '/pay',
  getParentRoute: () => TIdRoute,
} as any)
const TIdIssueRoute = TIdIssueRouteImport.update({
  id: '/issue',
  path: '/issue',
  getParentRoute: () => TIdRoute,
} as any)
const TIdConfirmRoute = TIdConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => TIdRoute,
} as any)
const SellerTxnIdRoute = SellerTxnIdRouteImport.update({
  id: '/seller/txn/$id',
  path: '/seller/txn/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerShareIdRoute = SellerShareIdRouteImport.update({
  id: '/seller/share/$id',
  path: '/seller/share/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerTxnIdIndexRoute = SellerTxnIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SellerTxnIdRoute,
} as any)
const SellerTxnIdRespondRoute = SellerTxnIdRespondRouteImport.update({
  id: '/respond',
  path: '/respond',
  getParentRoute: () => SellerTxnIdRoute,
} as any)
const SellerTxnIdDispatchRoute = SellerTxnIdDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => SellerTxnIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/seller/create': typeof SellerCreateRoute
  '/t/$id': typeof TIdRouteWithChildren
  '/seller/': typeof SellerIndexRoute
  '/seller/share/$id': typeof SellerShareIdRoute
  '/seller/txn/$id': typeof SellerTxnIdRouteWithChildren
  '/t/$id/confirm': typeof TIdConfirmRoute
  '/t/$id/issue': typeof TIdIssueRoute
  '/t/$id/pay': typeof TIdPayRoute
  '/t/$id/protected': typeof TIdProtectedRoute
  '/t/$id/receipt': typeof TIdReceiptRoute
  '/t/$id/': typeof TIdIndexRoute
  '/seller/txn/$id/dispatch': typeof SellerTxnIdDispatchRoute
  '/seller/txn/$id/respond': typeof SellerTxnIdRespondRoute
  '/seller/txn/$id/': typeof SellerTxnIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/seller/create': typeof SellerCreateRoute
  '/seller': typeof SellerIndexRoute
  '/seller/share/$id': typeof SellerShareIdRoute
  '/t/$id/confirm': typeof TIdConfirmRoute
  '/t/$id/issue': typeof TIdIssueRoute
  '/t/$id/pay': typeof TIdPayRoute
  '/t/$id/protected': typeof TIdProtectedRoute
  '/t/$id/receipt': typeof TIdReceiptRoute
  '/t/$id': typeof TIdIndexRoute
  '/seller/txn/$id/dispatch': typeof SellerTxnIdDispatchRoute
  '/seller/txn/$id/respond': typeof SellerTxnIdRespondRoute
  '/seller/txn/$id': typeof SellerTxnIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/seller/create': typeof SellerCreateRoute
  '/t/$id': typeof TIdRouteWithChildren
  '/seller/': typeof SellerIndexRoute
  '/seller/share/$id': typeof SellerShareIdRoute
  '/seller/txn/$id': typeof SellerTxnIdRouteWithChildren
  '/t/$id/confirm': typeof TIdConfirmRoute
  '/t/$id/issue': typeof TIdIssueRoute
  '/t/$id/pay': typeof TIdPayRoute
  '/t/$id/protected': typeof TIdProtectedRoute
  '/t/$id/receipt': typeof TIdReceiptRoute
  '/t/$id/': typeof TIdIndexRoute
  '/seller/txn/$id/dispatch': typeof SellerTxnIdDispatchRoute
  '/seller/txn/$id/respond': typeof SellerTxnIdRespondRoute
  '/seller/txn/$id/': typeof SellerTxnIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/seller/create'
    | '/t/$id'
    | '/seller/'
    | '/seller/share/$id'
    | '/seller/txn/$id'
    | '/t/$id/confirm'
    | '/t/$id/issue'
    | '/t/$id/pay'
    | '/t/$id/protected'
    | '/t/$id/receipt'
    | '/t/$id/'
    | '/seller/txn/$id/dispatch'
    | '/seller/txn/$id/respond'
    | '/seller/txn/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/seller/create'
    | '/seller'
    | '/seller/share/$id'
    | '/t/$id/confirm'
    | '/t/$id/issue'
    | '/t/$id/pay'
    | '/t/$id/protected'
    | '/t/$id/receipt'
    | '/t/$id'
    | '/seller/txn/$id/dispatch'
    | '/seller/txn/$id/respond'
    | '/seller/txn/$id'
  id:
    | '__root__'
    | '/'
    | '/seller/create'
    | '/t/$id'
    | '/seller/'
    | '/seller/share/$id'
    | '/seller/txn/$id'
    | '/t/$id/confirm'
    | '/t/$id/issue'
    | '/t/$id/pay'
    | '/t/$id/protected'
    | '/t/$id/receipt'
    | '/t/$id/'
    | '/seller/txn/$id/dispatch'
    | '/seller/txn/$id/respond'
    | '/seller/txn/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SellerCreateRoute: typeof SellerCreateRoute
  TIdRoute: typeof TIdRouteWithChildren
  SellerIndexRoute: typeof SellerIndexRoute
  SellerShareIdRoute: typeof SellerShareIdRoute
  SellerTxnIdRoute: typeof SellerTxnIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/': {
      id: '/seller/'
      path: '/seller'
      fullPath: '/seller/'
      preLoaderRoute: typeof SellerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$id': {
      id: '/t/$id'
      path: '/t/$id'
      fullPath: '/t/$id'
      preLoaderRoute: typeof TIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/create': {
      id: '/seller/create'
      path: '/seller/create'
      fullPath: '/seller/create'
      preLoaderRoute: typeof SellerCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$id/': {
      id: '/t/$id/'
      path: '/'
      fullPath: '/t/$id/'
      preLoaderRoute: typeof TIdIndexRouteImport
      parentRoute: typeof TIdRoute
    }
    '/t/$id/receipt': {
      id: '/t/$id/receipt'
      path: '/receipt'
      fullPath: '/t/$id/receipt'
      preLoaderRoute: typeof TIdReceiptRouteImport
      parentRoute: typeof TIdRoute
    }
    '/t/$id/protected': {
      id: '/t/$id/protected'
      path: '/protected'
      fullPath: '/t/$id/protected'
      preLoaderRoute: typeof TIdProtectedRouteImport
      parentRoute: typeof TIdRoute
    }
    '/t/$id/pay': {
      id: '/t/$id/pay'
      path: '/pay'
      fullPath: '/t/$id/pay'
      preLoaderRoute: typeof TIdPayRouteImport
      parentRoute: typeof TIdRoute
    }
    '/t/$id/issue': {
      id: '/t/$id/issue'
      path: '/issue'
      fullPath: '/t/$id/issue'
      preLoaderRoute: typeof TIdIssueRouteImport
      parentRoute: typeof TIdRoute
    }
    '/t/$id/confirm': {
      id: '/t/$id/confirm'
      path: '/confirm'
      fullPath: '/t/$id/confirm'
      preLoaderRoute: typeof TIdConfirmRouteImport
      parentRoute: typeof TIdRoute
    }
    '/seller/txn/$id': {
      id: '/seller/txn/$id'
      path: '/seller/txn/$id'
      fullPath: '/seller/txn/$id'
      preLoaderRoute: typeof SellerTxnIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/share/$id': {
      id: '/seller/share/$id'
      path: '/seller/share/$id'
      fullPath: '/seller/share/$id'
      preLoaderRoute: typeof SellerShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/txn/$id/': {
      id: '/seller/txn/$id/'
      path: '/'
      fullPath: '/seller/txn/$id/'
      preLoaderRoute: typeof SellerTxnIdIndexRouteImport
      parentRoute: typeof SellerTxnIdRoute
    }
    '/seller/txn/$id/respond': {
      id: '/seller/txn/$id/respond'
      path: '/respond'
      fullPath: '/seller/txn/$id/respond'
      preLoaderRoute: typeof SellerTxnIdRespondRouteImport
      parentRoute: typeof SellerTxnIdRoute
    }
    '/seller/txn/$id/dispatch': {
      id: '/seller/txn/$id/dispatch'
      path: '/dispatch'
      fullPath: '/seller/txn/$id/dispatch'
      preLoaderRoute: typeof SellerTxnIdDispatchRouteImport
      parentRoute: typeof SellerTxnIdRoute
    }
  }
}

interface TIdRouteChildren {
  TIdConfirmRoute: typeof TIdConfirmRoute
  TIdIssueRoute: typeof TIdIssueRoute
  TIdPayRoute: typeof TIdPayRoute
  TIdProtectedRoute: typeof TIdProtectedRoute
  TIdReceiptRoute: typeof TIdReceiptRoute
  TIdIndexRoute: typeof TIdIndexRoute
}

const TIdRouteChildren: TIdRouteChildren = {
  TIdConfirmRoute: TIdConfirmRoute,
  TIdIssueRoute: TIdIssueRoute,
  TIdPayRoute: TIdPayRoute,
  TIdProtectedRoute: TIdProtectedRoute,
  TIdReceiptRoute: TIdReceiptRoute,
  TIdIndexRoute: TIdIndexRoute,
}

const TIdRouteWithChildren = TIdRoute._addFileChildren(TIdRouteChildren)

interface SellerTxnIdRouteChildren {
  SellerTxnIdDispatchRoute: typeof SellerTxnIdDispatchRoute
  SellerTxnIdRespondRoute: typeof SellerTxnIdRespondRoute
  SellerTxnIdIndexRoute: typeof SellerTxnIdIndexRoute
}

const SellerTxnIdRouteChildren: SellerTxnIdRouteChildren = {
  SellerTxnIdDispatchRoute: SellerTxnIdDispatchRoute,
  SellerTxnIdRespondRoute: SellerTxnIdRespondRoute,
  SellerTxnIdIndexRoute: SellerTxnIdIndexRoute,
}

const SellerTxnIdRouteWithChildren = SellerTxnIdRoute._addFileChildren(
  SellerTxnIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SellerCreateRoute: SellerCreateRoute,
  TIdRoute: TIdRouteWithChildren,
  SellerIndexRoute: SellerIndexRoute,
  SellerShareIdRoute: SellerShareIdRoute,
  SellerTxnIdRoute: SellerTxnIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
